Add Null Type in TS and Kotlin. Add Null Constant and Undefined Type in Typescript
alexisthedev/hephaestus pull request #3
Opened 2022-07-29 11:14 UTC by alexisthedev

2022-08-05 11:38 UTC, theosotr requested changes

2022-08-05 11:38 UTC, theosotr commented on src/ir/groovy_types.py
> +        raise Exception("Groovy does not support null types")
remove FIXME

2022-08-05 11:38 UTC, theosotr commented on src/ir/java_types.py
> +        # FIXME
same here

2022-08-05 11:38 UTC, theosotr commented on src/ir/kotlin_types.py
> +class NullType(KotlinBuiltin):
I think the parent of `NullType` should be `AnyType`.

2022-08-05 11:38 UTC, theosotr commented on src/ir/typescript_types.py
> +        super().__init__(name, primitive)
I think the object type should be the supertype of `NullType`.

2022-08-05 11:38 UTC, theosotr commented on src/ir/typescript_types.py
> +        super().__init__(name, primitive)
I think the object type should be the supertype of `UndefinedType`.

2022-08-05 11:44 UTC, theosotr commented
Just to be sure. What's the supertype of all types in TypeScript. I think it's not `any` because this type disables type checking. So, what's the supertype of e.g., `number`?

2022-08-09 12:12 UTC, alexisthedev commented
> Just to be sure. What's the supertype of all types in TypeScript? I think it's not `any` because this type disables type checking. So, what's the supertype of e.g., `number`?

The supertype of all types in TS is the `Any` type.

From what I gather from the docs, it holds that role alongside `unknown`, [with the only difference between the two being that `unknown` can **only** be assigned to any.](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#any-unknown-object-void-undefined-null-and-never-assignability)

This is not a surprise, as this is the default behavior of JavaScript (everything is of type any).

2022-08-09 12:52 UTC, theosotr commented
> > Just to be sure. What's the supertype of all types in TypeScript? I think it's not `any` because this type disables type checking. So, what's the supertype of e.g., `number`?
> 
> The supertype of all types in TS is the `Any` type.
> 
> From what I gather from the docs, it holds that role alongside `unknown`, [with the only difference between the two being that `unknown` can **only** be assigned to any.](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#any-unknown-object-void-undefined-null-and-never-assignability)
> 
> This is not a surprise, as this is the default behavior of JavaScript (everything is of type any).

So, If the supertype in TS is `any`, is there any reason why we chose `ObjectType` as the supertype of `NumberType`, `NullType`, etc?

2022-08-16 17:12 UTC, alexisthedev commented
> So, If the supertype in TS is `any`, is there any reason why we chose `ObjectType` as the supertype of `NumberType`, `NullType`, etc?

Since 'any' in typescript bypasses typechecking having a 'AnyType' class in typescript_types.py would have no use as we would never pass AnyType to the generator. Hence we moved on with just using ObjectType.

2022-08-24 07:32 UTC, theosotr commented on src/ir/typescript_types.py
> +        return NumberType(primitive=True)
Why `primitive=True`?

2022-08-24 07:32 UTC, theosotr commented on src/ir/typescript_types.py
> +        return NumberType(primitive=True)
Same here

2022-08-24 07:58 UTC, merged